DTag\Bundles\UserBundle\Entity\User:
    type: entity
    table: core_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    attributeOverride:
        email:
            nullable: true
        emailCanonical:
            nullable: true
            unique: false
    fields:
        joinDate:
            type: date
            gedmo:
                timestampable:
                    on: create

    inheritanceType: JOINED

    discriminatorColumn:
        name: type
        type: string
    discriminatorMap:
        admin: DTag\Bundles\UserSystem\AdminBundle\Entity\User
        broker: DTag\Bundles\UserSystem\BrokerBundle\Entity\User
        moderator: DTag\Bundles\UserSystem\ModeratorBundle\Entity\User